spring:
  application:
    name: rsocket-broker-gossip1
  netty:
    leak-detection: paranoid
server:
  port: 10000

kin:
  rsocket:
    broker:
      port: 10001
      auth: false
      gossip:
        port: 10002
        seeds:
          - 0.0.0.0:11002

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

# logging
logging:
  level:
    root: info