spring:
  application:
    name: rsocket-broker
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        metadata:
#          rsocketSchemaPorts: tcp:${kin.rsocket.broker.port}
server:
  port: 9998

kin:
  rsocket:
    broker:
      port: 9999
      auth: true
      router: weightedStats

# management
management:
  server:
    port: 9998
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

# logging
logging:
  level:
    root: info