spring:
  application:
    name: rsocket-broker
  #  cloud:
  #    nacos:
  #      discovery:
  #        server-addr: 127.0.0.1:8848
  #        metadata:
  #          rsocketSchemaPorts: tcp:${kin.rsocket.broker.port}
  netty:
    leak-detection: paranoid
server:
  port: 10001

kin:
  rsocket:
    broker:
      port: 10000
      auth: true
      router: weightedStats

# management
management:
  server:
    port: ${server.port}
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      http: false
    export:
      prometheus:
        enabled: true
  trace:
    http:
      enabled: false

# logging
logging:
  level:
    root: info